spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/books
    platform: postgres
    username: bookstore
    password: example
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    schema: schema.sql
    data: data.sql
