version: "3.7"
services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_USER: bookstore
      POSTGRES_PASSWORD: example
      POSTGRES_DB: books
    ports:
      - 5432:5432
    volumes:
      - postgresdb:/var/lib/postgresql/data

volumes:
  postgresdb:
    name: postgresdb